# Generated by Django 4.2.1 on 2024-08-02 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_animeseries_remove_season_series_delete_episode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeseries',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='animeseries',
            old_name='episode_title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='animeseries',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='clips.animeseries')),
            ],
            options={
                'ordering': ['series', 'number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.RemoveField(
            model_name='animeseries',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='animeseries',
            name='episode_url',
        ),
        migrations.RemoveField(
            model_name='animeseries',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='animeseries',
            name='series_title',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='clips.season')),
            ],
            options={
                'ordering': ['season', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
