# Generated by Django 4.2.1 on 2024-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_alter_animeseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeseries',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
